
insert into doctor (id, address, email, name, password, phone_number, specialization) values (1, 'Room 1491', 'nbradforth0@msu.edu', 'Northrop Bradforth', 'bF4`,l+uzEAKH"s', '7956831797', 'Data Coordinator');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (2, '9th Floor', 'mhaville1@amazonaws.com', 'Maureene Haville', 'iL0+f''%vn+*Bl.ym', '7568516504', 'Budget/Accounting Analyst III');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (3, 'Room 249', 'nlosemann2@ezinearticles.com', 'Noelani Losemann', 'eW4{zO~m}Z{Xnv', '2046558844', 'Office Assistant II');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (4, '8th Floor', 'awhitcher3@ibm.com', 'Artie Whitcher', 'mK1#Llz_', '6879190523', 'Compensation Analyst');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (5, '15th Floor', 'mmarran4@mashable.com', 'Morgan Marran', 'qF2`~KU`@*516fVk', '1799979157', 'Senior Editor');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (6, 'Apt 306', 'glaw5@oracle.com', 'Gabbi Law', 'tH8)(NdT.', '7086430104', 'Help Desk Operator');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (7, 'Suite 72', 'mweedon6@bizjournals.com', 'Marleah Weedon', 'oT0.riutqx,`R9', '3411306796', 'Financial Analyst');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (8, '20th Floor', 'bstothard7@scientificamerican.com', 'Beatrix Stothard', 'hP5|DI4wsLAm', '1565412459', 'Automation Specialist I');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (9, 'Suite 74', 'fgoulbourne8@about.com', 'Fedora Goulbourne', 'dX3<0j%Mdu', '7703780756', 'Executive Secretary');
insert into doctor (id, address, email, name, password, phone_number, specialization) values (10, 'Suite 53', 'msiggery9@youku.com', 'Maddi Siggery', 'eS2"&4t}AY', '9317805441', 'Administrative Assistant II');