#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 641972373750-gierrkhcs1tle8089ebon4la52i31fhd.apps.googleusercontent.com
#            client-secret: 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